import type { Metadata } from "next";
import { Nabla } from "next/font/google";
import "./globals.css";

const nabla = Nabla({
  variable: "--font-nabla",
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nabla.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
